import streamlit as st
import streamlit.components.v1 as components
import requests
import json
import re
from datetime import datetime
from fpdf import FPDF

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "llama3.1"

PRD_PROMPT = """You are a senior Product Manager with 10+ years of experience at top tech companies. 
Your task is to generate a structured, implementation-ready Product Requirements Document (PRD).

Given the product/feature idea below, produce a complete PRD with ALL of the following sections. 
Be specific, opinionated, and actionable. Avoid vague language. Write for an engineering team that needs to build this.

PRODUCT IDEA:
{idea}

Generate the PRD in this EXACT format using these section headers:

## Problem Statement
[2-3 sentences. What pain exists, for whom, and why it matters now.]

## Objectives
[3-5 measurable goals this product/feature must achieve.]

## Target Users
[Who are the primary and secondary users. Be specific about their context and needs.]

## User Personas
[2 personas. Each with: Name, Role, Goals, Pain Points, Tech Comfort Level.]

## User Stories
[5-8 user stories in format: As a [user], I want to [action] so that [benefit].]

## Functional Requirements
[Numbered list of what the system must do. Group by feature area if needed.]

## Non-Functional Requirements
[Performance, security, scalability, accessibility constraints.]

## Acceptance Criteria
[For each major feature, define clear pass/fail criteria engineers can test against.]

## Assumptions & Dependencies
[What are you assuming to be true? What does this depend on externally?]

## Risks & Mitigations
[Top 3-5 risks with likelihood, impact, and mitigation strategy.]

## Success Metrics
[Quantifiable KPIs to measure if this product succeeds. Include baseline and target.]

## MVP Scope
[What is IN scope for v1. What is explicitly OUT of scope. What comes in v2.]

---
Be thorough. A junior PM or engineer should be able to start building from this document alone.
"""

def check_ollama_connection():
    try:
        response = requests.get("http://localhost:11434/api/tags", timeout=5)
        if response.status_code == 200:
            models = [m["name"] for m in response.json().get("models", [])]
            return True, models
        return False, []
    except Exception:
        return False, []

def check_model_available(models):
    return any(MODEL in m for m in models)

def generate_prd_stream(idea: str):
    payload = {
        "model": MODEL,
        "prompt": PRD_PROMPT.format(idea=idea),
        "stream": True,
        "options": {
            "temperature": 0.4,
            "top_p": 0.9,
            "num_predict": 4096,
        }
    }
    try:
        with requests.post(OLLAMA_URL, json=payload, stream=True, timeout=120) as response:
            response.raise_for_status()
            for line in response.iter_lines():
                if line:
                    chunk = json.loads(line.decode("utf-8"))
                    if not chunk.get("done"):
                        yield chunk.get("response", "")
    except requests.exceptions.ConnectionError:
        yield "\n\n❌ **Cannot connect to Ollama.** Make sure Ollama is running: `ollama serve`"
    except requests.exceptions.Timeout:
        yield "\n\n❌ **Request timed out.** The model may be loading — try again in a few seconds."
    except Exception as e:
        yield f"\n\n❌ **Error:** {str(e)}"

def build_download_content(idea: str, prd_content: str) -> str:
    return f"""# Product Requirements Document
Generated: {datetime.now().strftime("%B %d, %Y at %H:%M")}
Model: {MODEL} via Ollama

## Product Idea
{idea}

---

{prd_content}

---
*Generated by PRD Generator — github.com/siddhant7trivedi/sid_builds*
"""

def generate_pdf(idea: str, prd_content: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    def strip_inline(text: str) -> str:
        text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
        text = re.sub(r'\*(.*?)\*', r'\1', text)
        text = re.sub(r'`(.*?)`', r'\1', text)
        return text

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "Product Requirements Document", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}  |  Model: {MODEL}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    for line in prd_content.split('\n'):
        stripped = line.strip()
        if stripped.startswith('## '):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 8, strip_inline(stripped[3:]), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 11)
        elif stripped.startswith('### '):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 7, strip_inline(stripped[4:]), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 11)
        elif stripped.startswith('- ') or stripped.startswith('* '):
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 6, f"  - {strip_inline(stripped[2:])}", new_x="LMARGIN", new_y="NEXT")
        elif re.match(r'^\d+\.', stripped):
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 6, f"  {strip_inline(stripped)}", new_x="LMARGIN", new_y="NEXT")
        elif stripped == '---':
            pdf.set_draw_color(200, 200, 200)
            pdf.line(pdf.l_margin, pdf.get_y() + 2, pdf.w - pdf.r_margin, pdf.get_y() + 2)
            pdf.set_draw_color(0, 0, 0)
            pdf.ln(4)
        elif stripped.startswith('|'):
            cells = [c.strip() for c in stripped.split('|')[1:-1]]
            if all(set(c) <= {'-', ' ', ':'} for c in cells):
                continue
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 5, '  ' + '  |  '.join(strip_inline(c) for c in cells), new_x="LMARGIN", new_y="NEXT")
        elif stripped:
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 6, strip_inline(stripped), new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.ln(3)

    return bytes(pdf.output())

def clipboard_button(text: str):
    encoded = json.dumps(text)
    components.html(
        f"""
        <style>
          button {{
            background: white;
            border: 1px solid rgba(49,51,63,0.2);
            border-radius: 8px;
            padding: 5px 14px;
            cursor: pointer;
            font-size: 14px;
            font-family: "Source Sans Pro", sans-serif;
            width: 100%;
            color: #31333F;
            transition: border-color 0.15s, background 0.15s;
          }}
          button:hover {{ background: #f0f2f6; border-color: rgba(49,51,63,0.4); }}
        </style>
        <button id="copybtn" onclick="
          var text = {encoded};
          if (navigator.clipboard && navigator.clipboard.writeText) {{
            navigator.clipboard.writeText(text).then(function() {{
              document.getElementById('copybtn').innerText = '✓ Copied!';
              setTimeout(function() {{ document.getElementById('copybtn').innerText = '\U0001f4cb Copy'; }}, 2000);
            }}).catch(function() {{ fallback(text); }});
          }} else {{ fallback(text); }}
          function fallback(t) {{
            var ta = document.createElement('textarea');
            ta.value = t;
            ta.style.position = 'fixed';
            ta.style.left = '-9999px';
            document.body.appendChild(ta);
            ta.focus(); ta.select();
            document.execCommand('copy');
            document.body.removeChild(ta);
            document.getElementById('copybtn').innerText = '✓ Copied!';
            setTimeout(function() {{ document.getElementById('copybtn').innerText = '\U0001f4cb Copy'; }}, 2000);
          }}
        ">\U0001f4cb Copy</button>
        """,
        height=42,
    )

st.set_page_config(
    page_title="PRD Generator",
    page_icon="📋",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.markdown("""
<style>
    .main > div { padding-top: 2rem; }
    .stTextArea textarea { font-size: 15px; line-height: 1.6; }
    .status-box {
        padding: 0.75rem 1rem;
        border-radius: 8px;
        font-size: 14px;
        margin-bottom: 1rem;
    }
    .status-ok { background: #f0fdf4; border: 1px solid #bbf7d0; color: #166534; }
    .status-err { background: #fef2f2; border: 1px solid #fecaca; color: #991b1b; }
    div[data-testid="stMarkdownContainer"] h2 {
        font-size: 1.1rem;
        font-weight: 600;
        margin-top: 1.5rem;
        margin-bottom: 0.5rem;
        padding-bottom: 0.3rem;
        border-bottom: 1px solid #e5e7eb;
        color: #1f2937;
    }
    .section-card {
        background: #f9fafb;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 1rem 1.25rem;
        margin-bottom: 0.75rem;
    }
</style>
""", unsafe_allow_html=True)

col_title, col_info = st.columns([11, 1])
with col_title:
    st.markdown("# 📋 PRD Generator")
    st.markdown("Transform a raw product idea into an implementation-ready PRD. Powered by **Llama 3.1** running locally via Ollama.")
with col_info:
    st.markdown("<div style='margin-top:1.3rem'></div>", unsafe_allow_html=True)
    with st.popover("ℹ", use_container_width=True):
        st.markdown("""**Setup & Usage**

**Requirements**
```bash
pip install streamlit requests
```

**Run the app**
```bash
# 1. Start Ollama
ollama serve

# 2. Pull the model (first time only)
ollama pull llama3.1

# 3. Launch the app
streamlit run prd_generator.py
```

**What gets generated**
- Problem Statement · Objectives · Target Users · User Personas
- User Stories · Functional Requirements · Non-Functional Requirements
- Acceptance Criteria · Assumptions & Dependencies · Risks & Mitigations
- Success Metrics · MVP Scope

All output is copyable to clipboard or downloadable as Markdown or PDF.
""")

st.divider()

connected, available_models = check_ollama_connection()
model_ready = check_model_available(available_models)

col_status1, col_status2 = st.columns(2)
with col_status1:
    if connected:
        st.markdown('<div class="status-box status-ok">✅ Ollama is running</div>', unsafe_allow_html=True)
    else:
        st.markdown('<div class="status-box status-err">❌ Ollama not detected — run <code>ollama serve</code></div>', unsafe_allow_html=True)
with col_status2:
    if model_ready:
        st.markdown(f'<div class="status-box status-ok">✅ {MODEL} is available</div>', unsafe_allow_html=True)
    elif connected:
        st.markdown(f'<div class="status-box status-err">❌ {MODEL} not found — run <code>ollama pull llama3.1</code></div>', unsafe_allow_html=True)
    else:
        st.markdown('<div class="status-box status-err">⚠️ Model status unknown</div>', unsafe_allow_html=True)

st.markdown("### Describe your product or feature idea")
st.markdown("Be as specific or as rough as you like. More context = better PRD.")

idea_input = st.text_area(
    label="Product Idea",
    label_visibility="collapsed",
    placeholder=(
        "Example: A Slack bot that monitors our GitHub PRs and automatically posts "
        "a daily digest to the team channel — showing open PRs, who's blocking, "
        "and what's been merged. Target users are engineering teams of 5-20 people."
    ),
    height=140,
    key="idea_input"
)

col_btn, col_hint = st.columns([1, 4])
with col_btn:
    generate_clicked = st.button(
        "Generate PRD",
        type="primary",
        disabled=not (connected and model_ready),
        use_container_width=True
    )
with col_hint:
    if not connected:
        st.markdown("*Start Ollama first to enable generation*")
    elif not model_ready:
        st.markdown(f"*Pull the model first: `ollama pull {MODEL}`*")

if "prd_content" not in st.session_state:
    st.session_state.prd_content = ""
if "prd_idea" not in st.session_state:
    st.session_state.prd_idea = ""
if "prd_timestamp" not in st.session_state:
    st.session_state.prd_timestamp = ""

if generate_clicked:
    if not idea_input.strip():
        st.warning("Enter a product idea to get started.")
    else:
        st.session_state.prd_content = ""
        st.session_state.prd_idea = idea_input.strip()

        st.divider()
        st.markdown("### Generating PRD...")
        prd_placeholder = st.empty()
        full_prd = ""

        with st.spinner("Llama 3.1 is thinking..."):
            for chunk in generate_prd_stream(idea_input.strip()):
                full_prd += chunk
                prd_placeholder.markdown(full_prd)

        if full_prd and "❌" not in full_prd[:10]:
            st.session_state.prd_content = full_prd
            st.session_state.prd_timestamp = datetime.now().strftime("%Y%m%d_%H%M")
            st.rerun()

if st.session_state.prd_content:
    st.divider()

    col_head, col_copy, col_md, col_pdf = st.columns([5.5, 1, 1.4, 1.2])
    with col_head:
        st.markdown("### Generated PRD")
    with col_copy:
        st.markdown("<div style='margin-top:0.35rem'></div>", unsafe_allow_html=True)
        clipboard_button(st.session_state.prd_content)
    with col_md:
        st.markdown("<div style='margin-top:0.35rem'></div>", unsafe_allow_html=True)
        download_content = build_download_content(st.session_state.prd_idea, st.session_state.prd_content)
        st.download_button(
            label="⬇ Markdown",
            data=download_content,
            file_name=f"PRD_{st.session_state.prd_timestamp}.md",
            mime="text/markdown",
            use_container_width=True,
        )
    with col_pdf:
        st.markdown("<div style='margin-top:0.35rem'></div>", unsafe_allow_html=True)
        pdf_bytes = generate_pdf(st.session_state.prd_idea, st.session_state.prd_content)
        st.download_button(
            label="⬇ PDF",
            data=pdf_bytes,
            file_name=f"PRD_{st.session_state.prd_timestamp}.pdf",
            mime="application/pdf",
            use_container_width=True,
        )

    st.markdown(st.session_state.prd_content)
    st.caption(f"Generated · Model: {MODEL}")

