import streamlit as st
import requests
import json
from datetime import datetime

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "llama3.1"

PRD_PROMPT = """You are a senior Product Manager with 10+ years of experience at top tech companies. 
Your task is to generate a structured, implementation-ready Product Requirements Document (PRD).

Given the product/feature idea below, produce a complete PRD with ALL of the following sections. 
Be specific, opinionated, and actionable. Avoid vague language. Write for an engineering team that needs to build this.

PRODUCT IDEA:
{idea}

Generate the PRD in this EXACT format using these section headers:

## Problem Statement
[2-3 sentences. What pain exists, for whom, and why it matters now.]

## Objectives
[3-5 measurable goals this product/feature must achieve.]

## Target Users
[Who are the primary and secondary users. Be specific about their context and needs.]

## User Personas
[2 personas. Each with: Name, Role, Goals, Pain Points, Tech Comfort Level.]

## User Stories
[5-8 user stories in format: As a [user], I want to [action] so that [benefit].]

## Functional Requirements
[Numbered list of what the system must do. Group by feature area if needed.]

## Non-Functional Requirements
[Performance, security, scalability, accessibility constraints.]

## Acceptance Criteria
[For each major feature, define clear pass/fail criteria engineers can test against.]

## Assumptions & Dependencies
[What are you assuming to be true? What does this depend on externally?]

## Risks & Mitigations
[Top 3-5 risks with likelihood, impact, and mitigation strategy.]

## Success Metrics
[Quantifiable KPIs to measure if this product succeeds. Include baseline and target.]

## MVP Scope
[What is IN scope for v1. What is explicitly OUT of scope. What comes in v2.]

---
Be thorough. A junior PM or engineer should be able to start building from this document alone.
"""

def check_ollama_connection():
    try:
        response = requests.get("http://localhost:11434/api/tags", timeout=5)
        if response.status_code == 200:
            models = [m["name"] for m in response.json().get("models", [])]
            return True, models
        return False, []
    except Exception:
        return False, []

def check_model_available(models):
    return any(MODEL in m for m in models)

def generate_prd_stream(idea: str):
    payload = {
        "model": MODEL,
        "prompt": PRD_PROMPT.format(idea=idea),
        "stream": True,
        "options": {
            "temperature": 0.4,
            "top_p": 0.9,
            "num_predict": 4096,
        }
    }
    try:
        with requests.post(OLLAMA_URL, json=payload, stream=True, timeout=120) as response:
            response.raise_for_status()
            for line in response.iter_lines():
                if line:
                    chunk = json.loads(line.decode("utf-8"))
                    if not chunk.get("done"):
                        yield chunk.get("response", "")
    except requests.exceptions.ConnectionError:
        yield "\n\n❌ **Cannot connect to Ollama.** Make sure Ollama is running: `ollama serve`"
    except requests.exceptions.Timeout:
        yield "\n\n❌ **Request timed out.** The model may be loading — try again in a few seconds."
    except Exception as e:
        yield f"\n\n❌ **Error:** {str(e)}"

def build_download_content(idea: str, prd_content: str) -> str:
    return f"""# Product Requirements Document
Generated: {datetime.now().strftime("%B %d, %Y at %H:%M")}
Model: {MODEL} via Ollama

## Product Idea
{idea}

---

{prd_content}

---
*Generated by PRD Generator — github.com/siddhant7trivedi/sid_builds*
"""

st.set_page_config(
    page_title="PRD Generator",
    page_icon="📋",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.markdown("""
<style>
    .main > div { padding-top: 2rem; }
    .stTextArea textarea { font-size: 15px; line-height: 1.6; }
    .status-box {
        padding: 0.75rem 1rem;
        border-radius: 8px;
        font-size: 14px;
        margin-bottom: 1rem;
    }
    .status-ok { background: #f0fdf4; border: 1px solid #bbf7d0; color: #166534; }
    .status-err { background: #fef2f2; border: 1px solid #fecaca; color: #991b1b; }
    div[data-testid="stMarkdownContainer"] h2 {
        font-size: 1.1rem;
        font-weight: 600;
        margin-top: 1.5rem;
        margin-bottom: 0.5rem;
        padding-bottom: 0.3rem;
        border-bottom: 1px solid #e5e7eb;
        color: #1f2937;
    }
    .section-card {
        background: #f9fafb;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 1rem 1.25rem;
        margin-bottom: 0.75rem;
    }
</style>
""", unsafe_allow_html=True)

col_title, col_info = st.columns([11, 1])
with col_title:
    st.markdown("# 📋 PRD Generator")
    st.markdown("Transform a raw product idea into an implementation-ready PRD. Powered by **Llama 3.1** running locally via Ollama.")
with col_info:
    st.markdown("<div style='margin-top:1.3rem'></div>", unsafe_allow_html=True)
    with st.popover("ℹ", use_container_width=True):
        st.markdown("""**Setup & Usage**

**Requirements**
```bash
pip install streamlit requests
```

**Run the app**
```bash
# 1. Start Ollama
ollama serve

# 2. Pull the model (first time only)
ollama pull llama3.1

# 3. Launch the app
streamlit run prd_generator.py
```

**What gets generated**
- Problem Statement · Objectives · Target Users · User Personas
- User Stories · Functional Requirements · Non-Functional Requirements
- Acceptance Criteria · Assumptions & Dependencies · Risks & Mitigations
- Success Metrics · MVP Scope

All output is downloadable as Markdown or plain text.
""")

st.divider()

connected, available_models = check_ollama_connection()
model_ready = check_model_available(available_models)

col_status1, col_status2 = st.columns(2)
with col_status1:
    if connected:
        st.markdown('<div class="status-box status-ok">✅ Ollama is running</div>', unsafe_allow_html=True)
    else:
        st.markdown('<div class="status-box status-err">❌ Ollama not detected — run <code>ollama serve</code></div>', unsafe_allow_html=True)
with col_status2:
    if model_ready:
        st.markdown(f'<div class="status-box status-ok">✅ {MODEL} is available</div>', unsafe_allow_html=True)
    elif connected:
        st.markdown(f'<div class="status-box status-err">❌ {MODEL} not found — run <code>ollama pull llama3.1</code></div>', unsafe_allow_html=True)
    else:
        st.markdown('<div class="status-box status-err">⚠️ Model status unknown</div>', unsafe_allow_html=True)

st.markdown("### Describe your product or feature idea")
st.markdown("Be as specific or as rough as you like. More context = better PRD.")

idea_input = st.text_area(
    label="Product Idea",
    label_visibility="collapsed",
    placeholder=(
        "Example: A Slack bot that monitors our GitHub PRs and automatically posts "
        "a daily digest to the team channel — showing open PRs, who's blocking, "
        "and what's been merged. Target users are engineering teams of 5-20 people."
    ),
    height=140,
    key="idea_input"
)

col_btn, col_hint = st.columns([1, 4])
with col_btn:
    generate_clicked = st.button(
        "Generate PRD",
        type="primary",
        disabled=not (connected and model_ready),
        use_container_width=True
    )
with col_hint:
    if not connected:
        st.markdown("*Start Ollama first to enable generation*")
    elif not model_ready:
        st.markdown(f"*Pull the model first: `ollama pull {MODEL}`*")

if generate_clicked:
    if not idea_input.strip():
        st.warning("Enter a product idea to get started.")
    else:
        st.divider()
        st.markdown("### Generated PRD")

        prd_placeholder = st.empty()
        full_prd = ""

        with st.spinner("Llama 3.1 is thinking..."):
            for chunk in generate_prd_stream(idea_input.strip()):
                full_prd += chunk
                prd_placeholder.markdown(full_prd)

        if full_prd and "❌" not in full_prd[:10]:
            st.divider()

            download_content = build_download_content(idea_input.strip(), full_prd)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M")
            filename = f"PRD_{timestamp}.md"

            col_dl1, col_dl2, col_spacer = st.columns([1, 1, 3])
            with col_dl1:
                st.download_button(
                    label="⬇ Download as Markdown",
                    data=download_content,
                    file_name=filename,
                    mime="text/markdown",
                    use_container_width=True
                )
            with col_dl2:
                st.download_button(
                    label="⬇ Download as Text",
                    data=download_content,
                    file_name=filename.replace(".md", ".txt"),
                    mime="text/plain",
                    use_container_width=True
                )

            st.caption(f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')} · Model: {MODEL}")

